### ISSUE TITLE
Improve documentation for slide notes

### ISSUE THREAD

**Issue by sumeetattree** [pythonicrubyist/ruby_powerpoint#11]
It took me too long to figure out that the last entry in the ppt note array is the slide number. Could you please document this?

Another suggestion I would like to make is to return the notes_content as a hash instead of an array.

``` 
{
  <slide_number>: [note_content]
}

**Comment by pythonicrubyist** [comment]
@sumeetattree  I will update the docs, but I can not change the format of notes_content because fo backwards-compatibility issues.
