### ISSUE TITLE
Iterating over slide notes thrown NoMethodError: undefined method 'xpath' for nil:NilClass

### ISSUE THREAD

**Issue by sumeetattree** [pythonicrubyist/ruby_powerpoint#12]
Iterating over slide notes when notes are missing for some of slides throws this error.

This is the offending line:  https://github.com/pythonicrubyist/ruby_powerpoint/blob/8563eca97f2f324f06419de14e0a00f37a787652/lib/ruby_powerpoint/slide.rb#L86

It is really problematic because there's no clean way to recover from this error without using `rescue nil`.

Edit: I checked the code again with the sample.pptx included in the specs/fixtures but couldn't reproduce it with sample.pptx. Not sure what could be causing it. I have 3 ppts and all of them exhibit the same behavior. I am afraid I am unable to share those ppts I'll see if I can try reproducing it with the included sample.pptx

**Comment by pythonicrubyist** [comment]
@sumeetattree it will be very difficult for me to fix this without reproducible steps and files.
