### ISSUE TITLE
Is it possible to extract entire slides (not just the data)?

### ISSUE THREAD

**Issue by Ada323** [pythonicrubyist/ruby_powerpoint#13]
Hello,

I was wondering whether this library supports extracting entire powerpoint slides (rather than just the data)? Ideally I'm hoping to create a new file from a subset of the slides in a larger powerpoint presentation. 

Thank you!

**Comment by pythonicrubyist** [comment]
@Ada323 unfortunately this functionality is not currently supported. I have added it to the backlog and hopefully will be included in future releases.
