### ISSUE TITLE
bug export images

### ISSUE THREAD

**Issue by stefanschauer** [pythonicrubyist/ruby_powerpoint#7]
I followed the example and wanted to export the images of a pptx like this:
deck.slides.each do |slide|
  File.open('temp.jpg', 'w'){|f| f.puts slide.images[0]}
end

the saved files are not valid images.
when I open them in an editor the only contain the line: #<Zip::InputStream:
are the generated files zip that need to be uncompressed?

**Comment by pythonicrubyist** [comment]
@stefanschauer this should not happen unless our powerpoint is formated in a non-standard format. How was your powerpoint file generated initially? Google Slides? MS office? on a Mac?
